### ISSUE TITLE
Acercar a registro desde Forma "Issues" da error

### ISSUE THREAD

**Issue by niclopup** [solop-develop/frontend-core#1917]
## Bug report

Se intenta navegar a una Solicitud desde la forma "Issues" pero da error y no abre la ventana de Solicitudes.

![image](https://github.com/solop-develop/frontend-core/assets/31936815/5df9fb4a-7d3e-49a5-90e5-82dcc1d9782c)

![image](https://github.com/solop-develop/frontend-core/assets/31936815/7635deb6-9f7d-42a6-8a80-ec2d7531f6e0)

Error:

```
<html>
<body>
<!--StartFragment--><div data-v-be34583a="" class="el-dialog__wrapper" style="box-sizing: inherit; position: fixed; inset: 0px; overflow: auto; margin: 0px; color: rgb(0, 0, 0); font-family: &quot;Helvetica Neue&quot;, Helvetica, &quot;PingFang SC&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; z-index: 2007;"><div role="dialog" aria-modal="true" aria-label="dialog" class="el-dialog" style="box-sizing: border-box; margin: 15vh auto 0px; background: rgb(255, 255, 255); border-radius: 2px; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 3px; width: 1152px; transform: none; left: 0px; position: relative;"><div class="el-dialog__body" style="box-sizing: inherit; padding: 10px 20px; color: rgb(96, 98, 102); font-size: 14px; word-break: break-all; max-height: 90%; overflow: auto;"><div data-v-be34583a="" class="el-table el-table--fit el-table--border el-table--enable-row-hover el-table--enable-row-transition el-table--medium" style="box-sizing: border-box; position: relative; overflow: hidden; -webkit-box-flex: 1; flex: 1 1 0%; width: 1112px; max-width: 100%; background-color: rgb(255, 255, 255); font-size: 14px; color: rgb(96, 98, 102); border-right: none; border-bottom: none; border-top: 1px solid rgb(223, 230, 236); border-left: 1px solid rgb(223, 230, 236); border-image: initial;"><div class="el-table__body-wrapper is-scrolling-none" style="box-sizing: inherit; width: 1111px; overflow: hidden; position: relative;">
TypeError: e.zoomIssues is not a function at click (http://demo1.solopcloud.com/static/js/chunk-a3c4ef7c.e93acc93.js:1:71672) at rt (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:11674) at o.n (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:13494) at rt (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:11674) at Mn.e.$emit (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:26570) at o.handleClick (http://demo1.solopcloud.com/static/js/chunk-elementUI.2689c4ff.js:9:187855) at rt (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:11674) at HTMLButtonElement.n (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:13494) at Ji.a._wrapper (http://demo1.solopcloud.com/static/js/chunk-libs.56c35b1b.js:70:52151)
--


</div></div></div></div></div><br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>

```
#### Steps to reproduce

1. [xxx]
2. [xxx]
3. [xxxx]

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version: Front:  3.4.5

**Comment by niclopup** [comment]
No funciona.

lleva a la ventana pero no se ve el registro, queda registro vacío

![Image](https://github.com/user-attachments/assets/86ccab87-745b-4eed-b073-41d0bc49e634)


Debería llevar a la ventana "todas las solicitudes" ya q "Solicitudes" sólo mostrarían las asignadas a uno.
