### ISSUE TITLE
Problema en informe financiero

### ISSUE THREAD

**Issue by mgarciaQ76** [solop-develop/frontend-core#2756]
## Bug report

Se selecciona el informe financiero ventas por contrato. Seleccionando mismos filtros no trae misma info vue que zk

Parámetros: Org Laistar, período 01/2024
Adjunto comparativa vue y zk
Detectado en instancia 24816

#### Steps to reproduce

1. [Ingresar a informe financiero]
2. [Seleccionar informe, parámetros y ejecutar]

#### Screenshot or Gif（截图或动态图）

![informe financiero zk](https://github.com/user-attachments/assets/97c5b06c-fcae-4add-8d57-8d504cbf2336)
![informe financiero vue](https://github.com/user-attachments/assets/3148b61b-5b5f-4e97-96ce-d3c5dd5766c4)

#### Expected behavior

Que brinde información consistente con zk

#### Other relevant information
- Your OS:
- Web Browser:
- Node.js version:
- adempiere-vue version:

 Solop
 Nombre de Implementación:

 ${ADEMPIERE_VERSION} 20240912-1419
 Fecha Versión:

 miércoles, 02 de octubre de 2024, 12:00:00 a. m.
 Número de versión:

 3.9.4
 Versión del Back-End:

 3.8.005-r-17.10-v-1
 Versión del Dictionary RS:

 1.4.9
 Versión del Motor de Reporte:

 1.0.0-dev
 Versión del S3 Gateway RS:

 1.2.7
 Versión del Front-End:

 4.4.017

**Comment by yamelsenih** [comment]
Hola, una sugerencia. Es bueno copiar y pegar los parámetros para que sea más facil ubicarse, en este caso sería `101 - Ventas por Contrato (M)`

**Comment by yamelsenih** [comment]
```
2024-10-16T16:39:38.597595764Z ===========> FinReport.process: java.lang.NullPointerException [44]
2024-10-16T16:39:38.597641741Z java.lang.NullPointerException
2024-10-16T16:39:38.597645669Z   at org.compiere.report.FinReport.lambda$setNameAndDescription$21(FinReport.java:1215)
2024-10-16T16:39:38.597648795Z   at org.compiere.util.Trx.run(Trx.java:529)
2024-10-16T16:39:38.597651691Z   at org.compiere.util.Trx.run(Trx.java:497)
2024-10-16T16:39:38.597654567Z   at org.compiere.report.FinReport.setNameAndDescription(FinReport.java:1211)
2024-10-16T16:39:38.597657512Z   at org.compiere.report.FinReport.insertLineSource(FinReport.java:1061)
2024-10-16T16:39:38.597660418Z   at org.compiere.report.FinReport.lambda$insertLineDetail$16(FinReport.java:940)
2024-10-16T16:39:38.597663333Z   at org.compiere.util.Trx.run(Trx.java:529)
2024-10-16T16:39:38.597666148Z   at org.compiere.util.Trx.run(Trx.java:497)
2024-10-16T16:39:38.597669014Z   at org.compiere.report.FinReport.insertLineDetail(FinReport.java:936)
2024-10-16T16:39:38.597671879Z   at org.compiere.report.FinReport.doIt(FinReport.java:156)
2024-10-16T16:39:38.597674734Z   at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
2024-10-16T16:39:38.597677610Z   at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
2024-10-16T16:39:38.597680595Z
```

Esto es local sin patches. Es bueno saber si en una instancia con patches pasa lo mismo con el log

**Comment by yamelsenih** [comment]
El error lo da la clase `FindReport`, esta clase no valida contra null antes de llamar un método que probablemente devuelva null.
![image](https://github.com/user-attachments/assets/64fdcc84-5338-422a-89d5-f3593841fd35)
![image](https://github.com/user-attachments/assets/98e2e9d6-7fe9-4d88-9217-47c0c9b342b5)

En ZK me da el mismo error sobre la instancia de `dev` sin patches:

https://github.com/user-attachments/assets/bcfac5cd-4e87-4478-be8d-5e65186d67ad

```
===========> FinReport.process: java.lang.NullPointerException [110]
java.lang.NullPointerException
	at org.compiere.report.FinReport.lambda$setNameAndDescription$21(FinReport.java:1215)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.report.FinReport.setNameAndDescription(FinReport.java:1211)
	at org.compiere.report.FinReport.insertLineSource(FinReport.java:1061)
	at org.compiere.report.FinReport.lambda$insertLineDetail$16(FinReport.java:940)
	at org.compiere.util.Trx.run(Trx.java:529)
	at org.compiere.util.Trx.run(Trx.java:497)
	at org.compiere.report.FinReport.insertLineDetail(FinReport.java:936)
	at org.compiere.report.FinReport.doIt(FinReport.java:156)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:176)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:129)
```
